### PR TITLE
Feat: `screen` shortcut for `100vh` and `100vw`

### PR DESCRIPTION
**Pull request by oskar-gmerek**
Enables new classes for sizing.

`w:screen` as equivalent to `w:100vw`, 
`h:screen` as equivalent to `h:100vh` 

and so on for: 

- `width`, 
- `height`, 
- `min-width`, 
- `min-w`,
- `max-width`, 
- `max-w`,
- `min-height`, 
- `min-h`,
- `max-height`, 
- `max-h`.

Btw. Happy New Year! 🎉

### CODE REVIEW

**Comment by 1aron** [comment]
We've considered this semantic value. In fact, the viewport is not exactly equal to the screen, and the viewport will be smaller than the screen size.

So in terms of rationality, we have not done so for the time being.

**Comment by oskar-gmerek** [comment]
What about changing `screen` to `vp` | `vport` | `viewport` ?  I personally think the screen is intuitive as a short for the viewport. But, of course, you have the right, is not equal to it.

Anyway, I believe there should be a short for it. So my next proposition is simple `vp` | `vport` | `viewport`.

**Comment by 1aron** [comment]
> What about changing `screen` to `vp` | `vport` | `viewport` ? I personally think the screen is intuitive as a short for the viewport. But, of course, you have the right, is not equal to it.
> 
> Anyway, I believe there should be a short for it. So my next proposition is simple `vp` | `vport` | `viewport`.

How about semantic classes?
```html
<div class="width:100vw height:100vh">
<div class="vw vh">
```
```html
<div class="max-width:100vw max-height:100vh">
<div class="max-vw max-vh">
```
`vw` and `vh` probably make sense, since they are native CSS units.

**Comment by 1aron** [comment]
🎉 The feature has been released in [v2.0.0-beta.102](https://github.com/master-co/css/releases/tag/v2.0.0-beta.102)

**Pull request closed without merging**
